version: '3.4'

services:
  sqldata:
    container_name: sqldata
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass1word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - alchemy-sqldata:/var/opt/mssql

  sqlalchemycompose:
    container_name: api
    build: .
    #command: ["sh", "-c", "python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 80"]
    #command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/app
    depends_on:
      - sqldata

volumes:
  alchemy-sqldata:
    external: false

  

  
