version: '3.4'

services:
  sqldata:
    container_name: sqldata
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"

  sqlalchemycompose:
    container_name: api
    build: .
    ports:
      - 80:80
    volumes:
      - .:/app
    depends_on:
      - sqldata

  

  
